namespaces:
  ingress:
  argocd:
  
helmRepos:
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
  argocd: https://argoproj.github.io/argo-helm
apps:
  ingress-nginx:
    enabled: true
    wait: true # wait till ready, else it will to call the ingress admission webhooks
    namespace: ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.0.19
    valuesFiles:
      - ./ingress-nginx/values.yaml
    priority: -90
  argocd:
    enabled: true
    namespace: argocd
    chart: argo/argo-cd
    version: 5.4.4
    valuesFiles:
      - ./argo/values.yaml
    priority: -85


